backend = "glx";
corner-radius = 14;
rounded-corners-exclude = [
  "window_type != 'normal' && window_type != 'dialog'",
  "_NET_WM_STATE@[*]:a = '_NET_WM_STATE_MAXIMIZED_VERT'",
  "_NET_WM_STATE@[*]:a = '_NET_WM_STATE_MAXIMIZED_HORZ'",
  "_NET_WM_STATE@[*]:a = '_NET_WM_STATE_FULLSCREEN'"
];

window-shader-fg-rule = [
  "@SHADER_PATH@:(window_type = 'normal' || window_type = 'dialog') && _NET_FRAME_EXTENTS@[0]:32c = 0 && _NET_FRAME_EXTENTS@[2]:32c = 0"
];
